version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: jenkins
    hostname: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


